# version: 0.2
# phases:
#   install:
#     runtime-versions:
#       nodejs: 14
#     commands:
#       - echo "Installing dependencies..."
#       - npm install
#   build:
#     commands:
#       - echo "Building React App..."
#       - npm run build
#   post_build:
#     commands:
#       - echo "Updating files in the S3 bucket..."
#       - aws s3 sync build/ s3://codepipeline-birthday-app --delete


version: 0.2
phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React App..."
      - npm run build
  artifacts:
    files:
      - '**/*'
      discard-paths: no
      base-directory: build

