version: 0.2
phases:
  install:
    commands:
      - echo installing node...
      - curl -fsSL https://deb.nodesource.com/setup_15.x | bash -
      - apt-get install -y nodejs
      # - echo installing npm...
      # - apt-get install -y npm
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      # test
      - echo building...
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist